Feature/add scanner and containers
JupiterOne/graph-tenable-io pull request #190
Opened 2022-09-27 17:11 UTC by eXtremeX

2022-09-28 21:39 UTC, VDubber commented on CHANGELOG.md
> +| Service              | `tenable_scanner`              | `Service`       |
Is `Scanner` not an appropriate class for this entity?

2022-09-29 13:09 UTC, eXtremeX commented on CHANGELOG.md
> +| Service              | `tenable_scanner`              | `Service`       |
Hey @VDubber, I'm not sure. I've been seeing mentions of `Service` (class: `Service`) more and more in the Jira tickets as well as integrations doing things such as this one: https://github.com/JupiterOne/graph-checkmarx/blob/main/src/constants.ts#L26

We can do whatever is the best of course, just not sure what's the best way to handle these services/scanners in general :thinking:

2022-09-30 21:29 UTC, VDubber requested changes
Looking good! Just a few testing adds and we should be set.

2022-09-30 21:29 UTC, VDubber commented on src/steps/service/converters.ts
> +export function createAccountServiceRelationship(
Consider adding tests for this method.

2022-09-30 21:29 UTC, VDubber commented on src/steps/vulnerabilities/converters.ts
> +        firstFound: parseTimePropertyValue(vuln.first_found),
dates should have a suffix of `On`
`firstFound` -> `firstFoundOn`
`lastFound` -> `lastFoundOn`
etc

2022-09-30 21:29 UTC, VDubber commented on src/steps/vulnerabilities/converters.ts
> +        firstSeenOn: parseTimePropertyValue(vuln.first_found),
❤️

2022-09-30 21:29 UTC, VDubber commented on src/steps/vulnerabilities/converters.ts
> +        'scan.startedAt': parseTimePropertyValue(vuln.scan.started_at),
Should we convert this to `'scan.startedOn'`? Not really sure on this one.

2022-09-30 21:29 UTC, VDubber commented on src/tenable/TenableClient.ts
> +  private async paginated(
Please add test for `paginated` in TenableClient.test.ts or move to util and test there.

2022-09-30 21:29 UTC, VDubber commented on src/tenable/TenableClient.ts
> +    cb: (offset: number, limit: number) => Promise<number>,
nit: rename cb -> callback

2022-09-30 21:29 UTC, VDubber commented on src/tenable/TenableClient.ts
> +  public async iterateContainerRepositories(
Please add test coverage in Client file or in the individual step index.ts

2022-10-03 13:19 UTC, eXtremeX commented on src/steps/containers/converters.ts
> +  return {
Do you want me to refactor just that part over there or everywhere in this repo? Looks like this integration used some old pattern, so we were just trying to add our changes without changing/refactoring all of that. Quite a lot of converters functions aren't using createIntegrationEntity().

2022-10-03 13:21 UTC, eXtremeX commented on src/steps/containers/converters.ts
> +    publishedDate: parseTimePropertyValue(nvdFinding.published_date),
Yep, from the responses we're getting they're timestamps in `string` type.
![image](https://user-images.githubusercontent.com/8009142/193588019-5f602b6d-fe36-4301-8a8e-7f14d50c9623.png)

2022-10-03 22:04 UTC, VDubber commented on src/steps/containers/converters.ts
> +  return {
My preference is to always add the newest patterns but don't refactor everything. A refactor PR should be a separate task/ticket. It makes the PR easier to review but still pushes good patterns forward.

2022-10-11 15:37 UTC, VDubber approved these changes
Awesome work!

2022-10-12 12:41 UTC, merged