INT-4101 - Add Properties Fields to Tenable Vulnerability Finding
JupiterOne/graph-tenable-io pull request #192
Opened 2022-09-27 18:00 UTC by eXtremeX

This PR adds the following properties to the `tenable_vulnerability_finding`: `cve`, `cpe`, `description`, `recommendation`, `impact`.

Best merged/reviewed after https://github.com/JupiterOne/graph-tenable-io/pull/190 as running Tenable integration from main without any changes resulted in some error for the vulnerability step which got fixed in https://github.com/JupiterOne/graph-tenable-io/pull/190.

2022-09-30 21:51 UTC, VDubber commented on src/steps/vulnerabilities/converters.ts
>          references: vuln.plugin.see_also,
Is see_also an array of string?

2022-09-30 21:55 UTC, VDubber requested changes
A few minor updates are required to complete ticket ask. One comment is about separate CVE and CWE entities with relationships.

2022-09-30 21:55 UTC, VDubber commented on src/steps/vulnerabilities/converters.ts
> +        cve: vuln.plugin.cve || undefined,
I believe we build relationships to CVEs and CWEs. Please refer to the ticket and comments.

Also, the value for name & display_name need to be updated. See ticket.

2022-10-12 13:09 UTC, eXtremeX commented on src/steps/vulnerabilities/converters.ts
>          references: vuln.plugin.see_also,
Yes it is, it looks like this for an example:

```
[
  'https://crbug.com/1343104',
  'http://www.nessus.org/u?97263b93',
  'https://crbug.com/1358907',
  'https://crbug.com/1319229',
  'https://crbug.com/1320139',
  'https://crbug.com/1323488',
  'https://crbug.com/1342722',
  'https://crbug.com/1348415',
  'https://crbug.com/1240065',
  'https://crbug.com/1302813',
  'https://crbug.com/1303306',
  'https://crbug.com/1317904',
  'https://crbug.com/1328708',
  'https://crbug.com/1322812',
  'https://crbug.com/1333623',
  'https://crbug.com/1300539',
  'https://crbug.com/1318791'
]
```

2022-10-19 15:51 UTC, VDubber commented on src/steps/containers/converters.ts
> +    createdAt: parseTimePropertyValue(image.createdAt),
Please change all dates properties to *On.
createdAt -> createdOn
including `lastScanned` -> `lastScannedOn`

2022-10-19 15:56 UTC, VDubber commented on src/steps/containers/converters.ts
> +    publishedDate: parseTimePropertyValue(nvdFinding.published_date),
publishedDate -> nvdPublishedOn
modifiedDate -> nvdModifiedOn

2022-10-19 16:07 UTC, VDubber commented on src/steps/vulnerabilities/converters.ts
> +        firstFound: parseTimePropertyValue(vuln.first_found),
please update to:
firstFoundOn
lastFoundOn

2022-10-19 16:09 UTC, VDubber commented on src/tenable/TenableClient.ts
> +const PAGE_ENTITY_COUNT_LIMIT = 10;
Why are we only pulling 10?

2022-10-19 16:09 UTC, VDubber commented on src/tenable/TenableClient.ts
> +const PAGE_ENTITY_COUNT_LIMIT = 10;
If you could add documentation around this so the next dev has context that'd be awesome.

2022-10-19 21:11 UTC, VDubber commented on src/steps/vulnerabilities/converters.ts
> +        cve: vuln.plugin.cve || undefined,
I reviewed the code post conversation with Stefan. Relationships are being created. 

I also spoke to Erica about the desired name changes and she concluded that no change was best.

2022-10-19 21:37 UTC, VDubber reviewed
When I executed the integration with the current change set I received the following msg:
```
Step "step-account" completed with status: success
Step "step-service" completed with status: success
Step "step-container-images" completed with status: success
Step "step-container-repositories" completed with status: success
Step "build-repository-images-relationships" completed with status: success
Step "step-container-reports" completed with status: success
Step "step-assets" completed with status: success
The following types were encountered but are not declared in the step's "types" field:
  - mapping_source_is_tenable_asset,
  - mapping_source_is_azure_vm

Step "step-vulnerabilities" completed with status: success
Step "build-asset-vuln-relationships" completed with status: success
The following types were encountered but are not declared in the step's "types" field:
  - mapping_source_has_tenable_asset

Step "build-vuln-cve-relationships" completed with status: success
The following types were encountered but are not declared in the step's "types" field:
  - mapping_source_is_cve

Step "step-users" completed with status: success

Undeclared types were detected!
To ensure that integration failures do not cause accidental data loss,
please ensure that all known entity and relationship types
collected by a step are declared in the step's "types" field.
```

I don't believe this is associated with your current work since these relationships were pre-existing. These errors are not to be ignored. Let's work toward getting them addressed the next round.

Added a handful of minor comments. Once addressed this is good to go!

2022-10-24 11:57 UTC, eXtremeX commented on src/tenable/TenableClient.ts
> +const PAGE_ENTITY_COUNT_LIMIT = 10;
This change was actually seen because this PR wasn't rebased with the `main` - `main` received this change in the previous PR. But that's a very good callout, I have just checked and the maximum limit is 1000, I have raised to that value and have updated the tests/recordings.

2022-10-24 11:58 UTC, eXtremeX commented
> When I executed the integration with the current change set I received the following msg:
> 
> ```
> Step "step-account" completed with status: success
> Step "step-service" completed with status: success
> Step "step-container-images" completed with status: success
> Step "step-container-repositories" completed with status: success
> Step "build-repository-images-relationships" completed with status: success
> Step "step-container-reports" completed with status: success
> Step "step-assets" completed with status: success
> The following types were encountered but are not declared in the step's "types" field:
>   - mapping_source_is_tenable_asset,
>   - mapping_source_is_azure_vm
> 
> Step "step-vulnerabilities" completed with status: success
> Step "build-asset-vuln-relationships" completed with status: success
> The following types were encountered but are not declared in the step's "types" field:
>   - mapping_source_has_tenable_asset
> 
> Step "build-vuln-cve-relationships" completed with status: success
> The following types were encountered but are not declared in the step's "types" field:
>   - mapping_source_is_cve
> 
> Step "step-users" completed with status: success
> 
> Undeclared types were detected!
> To ensure that integration failures do not cause accidental data loss,
> please ensure that all known entity and relationship types
> collected by a step are declared in the step's "types" field.
> ```
> 
> I don't believe this is associated with your current work since these relationships were pre-existing. These errors are not to be ignored. Let's work toward getting them addressed the next round.
> 
> Added a handful of minor comments. Once addressed this is good to go!

Yep that's spot on, it came with that. Sounds good, just wanted to focus on what was needed for this task!

2022-10-25 16:50 UTC, merged